name: ie-bank-frontend-dev

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: larbibenamour-fe-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # Build app
      - name: Build app
        run: |
          npm install
          npm run build -- --mode development

      # Deploy to Azure Web App
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: dist/
